blank_issues_enabled: false
contact_links:
  - name: Simple Changes Community Support
    url: https://github.com/bayhasoft/simple-changes/discussions/categories/how-do-i
    about: Please ask and answer questions here.
